 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tts", type: :request do
  # Tt. As you add validations to Tt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Tt.create! valid_attributes
      get tts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tt = Tt.create! valid_attributes
      get tt_url(tt)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tt_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tt = Tt.create! valid_attributes
      get edit_tt_url(tt)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Tt" do
        expect {
          post tts_url, params: { tt: valid_attributes }
        }.to change(Tt, :count).by(1)
      end

      it "redirects to the created tt" do
        post tts_url, params: { tt: valid_attributes }
        expect(response).to redirect_to(tt_url(Tt.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Tt" do
        expect {
          post tts_url, params: { tt: invalid_attributes }
        }.to change(Tt, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tts_url, params: { tt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tt" do
        tt = Tt.create! valid_attributes
        patch tt_url(tt), params: { tt: new_attributes }
        tt.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tt" do
        tt = Tt.create! valid_attributes
        patch tt_url(tt), params: { tt: new_attributes }
        tt.reload
        expect(response).to redirect_to(tt_url(tt))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tt = Tt.create! valid_attributes
        patch tt_url(tt), params: { tt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tt" do
      tt = Tt.create! valid_attributes
      expect {
        delete tt_url(tt)
      }.to change(Tt, :count).by(-1)
    end

    it "redirects to the tts list" do
      tt = Tt.create! valid_attributes
      delete tt_url(tt)
      expect(response).to redirect_to(tts_url)
    end
  end
end
